services:
  # nginx
  web:
    image: nginx:latest
    container_name: scribes-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/ssl
  app:
    container_name: scribes-app
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/html
  db:
    image: postgres:16.6
    container_name: scribes-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: scribes
      POSTGRES_USER: scribes
      POSTGRES_PASSWORD: scribes
  # redis

volumes:
  pgdata:
